version: '3.7'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    volumes:
      - ./:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=es01
      - cluster.name=elasticsearch
      - cluster.initial_master_nodes=es01
      - ELASTIC_PASSWORD=password
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
  